layout_spectrum: 0.9093496229033917
typography_spectrum: 0.791750789154321
color:
  brandStrength: 0.971507353708148
  lightness: 0.08511202223598957
  saturation: 0.5890282376203686
  rhythmicContrast: 0.04996951296925545
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  appId: '106171216118819'
  type: Crepps
  image: null
author:
  name: Joshua Crepps
  email: josh@crepps-hi.com
logo: null
name: Crepps Home Inspection
navigation:
  - name: About Me
    id: 1721f74c-1a19-4b7c-9470-40a8011d7e21
    type: content
  - name: Fees
    id: 07cec14e-5c73-4103-8c65-00b754aae17c
    type: content
title: Crepps Home Inspection
description: A bright idea
