author:
  name: Joshua Crepps
  email: josh@crepps-hi.com
title: A BRIGHT IDEA
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6917562
  brandStrength: 0.06272402
  lightness: 0.750896
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#FFFC01'
    - '#008D00'
    - '#787878'
  rhythmicContrast: 0.9247312
typography_spectrum: 0.5389015178661793
navigation:
  - name: About Us
    url: 'http://www.crepps-hi.com/AboutUs.html'
    type: external
layout_spectrum: 0.5268817
name: Crepps Home Inspection
