author:
  name: Joshua Crepps
  email: josh@crepps-hi.com
title: Crepps Home Inspection
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6917562
  brandStrength: 1
  lightness: 0.750896
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#FFFC01'
    - '#008D00'
    - '#787878'
  rhythmicContrast: 0.9247312
typography_spectrum: 0.5389015178661793
description: A bright idea!
navigation:
  - name: Fees
    id: 07cec14e-5c73-4103-8c65-00b754aae17c
    type: content
  - name: About Me
    id: 1721f74c-1a19-4b7c-9470-40a8011d7e21
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/creppshi/'
    type: external
layout_spectrum: 0.5268817
name: Crepps Home Inspection
