typography_spectrum: 0.5389015178661793
color:
  saturation: 0.6917562
  brandStrength: 0.06272402
  lightness: 0.750896
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#FFFC01'
    - '#008D00'
    - '#787878'
  rhythmicContrast: 0.9247312
layout_spectrum: 0.5268817
author:
  name: Joshua Crepps
  email: josh@crepps-hi.com
name: Crepps Home Inspection
navigation:
  - name: About Us
    url: 'http://www.crepps-hi.com/AboutUs.html'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Crepps Home Inspection
