typography_spectrum: 0.5389015178661793
color:
  brandStrength: 0.48451921925880015
  lightness: 0.9055592250078917
  saturation: 0.16545621608383954
  rhythmicContrast: 0.33156241686083376
  brandColors:
    - '#000000'
    - '#FFFB00'
    - '#008D00'
    - '#FF8000'
    - '#FF0000'
opengraph:
  appId: '106171216118819'
layout_spectrum: 0.7775581085588783
author:
  name: Joshua Crepps
  email: josh@crepps-hi.com
name: Crepps Home Inspection
navigation:
  - name: About Us
    url: 'http://www.crepps-hi.com/AboutUs.html'
    type: external
title: A BRIGHT IDEA
